services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: pony
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medical_api
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build: .
    ports:
      - "13000:3000"
    depends_on:
      - db